### PR TITLE
Corrected link to contributing file. Fixes #105.

### LINKED ISSUE #105: Broken link in README when using the --github-templates option
The link to the contributing infos should point to the `CONTRIBUTING.md` in the `.github` directory.

### PR DESCRIPTION
**Pull request by raphaelstolt**
The `CONTRIBUTING.md` inside the `.github` directory is now referenced.

### CODE REVIEW

File: src/Construct.php [hunk 1]
```diff
@@ -206,11 +208,18 @@ protected function docs()
     /**
      * Generate README.md file.
      *
+     * @param boolean $withGitHubTemplates Whether or not to set a reference to the .github/contributing file in the readme.
+     *
      * @return void
      */
-    protected function readme()
+    protected function readme($withGitHubTemplates = false)
```
Comment (jonathantorres) [inline src/Construct.php]: Maybe you can use `$this->settings->withGithubTemplates()` in this `readme()` method directly? instead of pass it around.

**Comment by jonathantorres** [comment]
Please rebase your branch so I can merge this in.

**Comment by raphaelstolt** [comment]
Will need a refactoring in the future as there are currently to much duplications on the stub files level.

**Comment by jonathantorres** [comment]
Agreed! There's a bunch of stub files!
